name: Deploy to cloudtype

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install CloudType CLI
        run: npm install -g @cloudtype/cli

      - name: Deploy to CloudType
        run: |
          ctype login --email ${{ secrets.CLOUDTYPE_EMAIL }} --password ${{ secrets.CLOUDTYPE_PASSWORD }}
          ctype use budlpili/admore
          ctype apply -f admore-frontend.yaml
        env:
          CLOUDTYPE_EMAIL: ${{ secrets.CLOUDTYPE_EMAIL }}
          CLOUDTYPE_PASSWORD: ${{ secrets.CLOUDTYPE_PASSWORD }}
