name: Deploy to CloudType

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install CloudType CLI
      run: |
        npm install -g @cloudtype/cli
        
    - name: Deploy to CloudType
      env:
        CLOUDTYPE_TOKEN: ${{ secrets.CLOUDTYPE_TOKEN }}
      run: |
        echo "CloudType CLI 설치 확인:"
        ctype --version
        
        echo "CloudType 토큰 로그인:"
        ctype login -t "$CLOUDTYPE_TOKEN"
        
        echo "배포 시작:"
        ctype apply -f admore-frontend.yaml
