name: Deploy to cloudtype

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: budlpili/admore
          stage: main
          yaml: |
            name: admore-frontend
            app: node@22
            options:
              ports: "80"
              healthz: /
            env:
              - name: REACT_APP_API_URL
                value: https://admore-backend.cloudtype.app
              - name: REACT_APP_WS_URL
                value: https://admore-backend.cloudtype.app
            buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
